"""
Export the Jakarta forecast-24h model (GRUHead, met-free) to JSON for pure-TS serving
in a Vercel function (no onnxruntime native dep). Dumps GRU + MLP-head weights, the
feature spec + standardization, and reference (seq,cov)->(mu,logsigma) pairs so the TS
re-implementation can be parity-checked exactly against PyTorch.

Run: vayu/.venv/Scripts/python.exe vayu/ml/export_forecast24_weights.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path
import numpy as np
import torch
from train_jakarta_variants import GRUHead
try: sys.stdout.reconfigure(encoding='utf-8')
except Exception: pass

HERE = Path(__file__).resolve().parent
PT = HERE / 'jakarta_forecast24_model.pt'
OUT = HERE / 'jakarta_forecast24_weights.json'

def main() -> int:
    ck = torch.load(PT, map_location='cpu', weights_only=False)
    sd = ck['state_dict']
    n_cov = len(ck['covs'])
    model = GRUHead(n_cov).eval()
    model.load_state_dict(sd)

    W = {k: v.cpu().numpy().tolist() for k, v in sd.items()}
    # reference pairs for TS parity (deterministic)
    torch.manual_seed(7); np.random.seed(7)
    n_lag = len(ck['lag_cols'])
    refs = []
    for _ in range(6):
        seq = torch.randn(1, n_lag, 2)
        cov = torch.randn(1, n_cov)
        with torch.no_grad():
            mu, ls = model(seq, cov)
        refs.append({'seq': seq.numpy().tolist()[0], 'cov': cov.numpy().tolist()[0],
                     'mu': float(mu[0]), 'logsigma': float(ls[0])})

    out = {
        'hidden': 64, 'n_cov': n_cov, 'n_lag': n_lag,
        'covs': ck['covs'], 'cov_mean': ck['cov_mean'], 'cov_std': ck['cov_std'],
        'pm_sd': ck['pm_sd'], 't_mean': ck['t_mean'], 't_sd': ck['t_sd'],
        'weights': W, 'refs': refs,
    }
    OUT.write_text(json.dumps(out), encoding='utf-8')
    # Also emit an inline TS module (underscore → inlines into the Vercel function bundle; avoids
    # a runtime JSON import). Explicit type annotation so tsc doesn't deep-infer the 0.5MB literal.
    js = json.dumps(out, separators=(',', ':'))
    ts = ('// AUTO-GENERATED by vayu/ml/export_forecast24_weights.py — do not hand-edit.\n'
          '// Jakarta forecast-24h model (GRUHead met-free): GRU + MLP-head weights, standardization, parity refs.\n'
          'export interface Forecast24Model {\n'
          '  hidden: number; n_cov: number; n_lag: number; covs: string[];\n'
          '  cov_mean: number[]; cov_std: number[]; pm_sd: number; t_mean: number; t_sd: number;\n'
          '  weights: Record<string, number[] | number[][]>;\n'
          '  refs: { seq: number[][]; cov: number[]; mu: number; logsigma: number }[];\n'
          '}\n'
          'export const FORECAST24: Forecast24Model = ' + js + ';\n')
    TS_OUT = HERE.parent.parent / 'api' / 'vayu' / '_forecast24_weights.ts'
    TS_OUT.write_text(ts, encoding='utf-8')
    print('wrote TS module', TS_OUT, TS_OUT.stat().st_size, 'bytes')
    print('weight keys:', list(W.keys()))
    for k, v in W.items():
        print('  ', k, np.array(v).shape)
    print('covs:', ck['covs'])
    print('n_cov', n_cov, 'n_lag', n_lag, 'pm_sd', round(ck['pm_sd'], 4), 't_mean', round(ck['t_mean'], 4), 't_sd', round(ck['t_sd'], 4))
    print('ref0: mu', round(refs[0]['mu'], 6), 'logsigma', round(refs[0]['logsigma'], 6))
    print('wrote', OUT.name, OUT.stat().st_size, 'bytes')
    return 0

if __name__ == '__main__':
    sys.exit(main())
